{% set name = "vollseg-napari" %}
{% set version = "2.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 298ef68e4b8bdc8befd95cfdb7ea35df465a908341b2046a9f8cfe9e96de16c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui >=0.4.0
    - napari >=0.4.13
    - napari-plugin-engine
    - python >={{ python_min }}
    - tensorflow
    - vollseg
    - psygnal
    - numpy
    - qtpy
    - tifffile

test:
  imports:
    - vollseg_napari
    - vollseg_napari._dock_widget
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kapoorlab/vollseg-napari
  summary: Irregular cell shape segmentation using VollSeg
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kapoorlab
