{% set name = "vollseg-napari" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vollseg-napari-{{ version }}.tar.gz
  sha256: 30a0342c3ebdcc991714ec3f7d5a4090104b953080591a27791ad49b38db4bc2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - magicgui >=0.4.0
    - napari >=0.4.13
    - napari-plugin-engine
    - python >=3.7
    - tensorflow
    - vollseg
    - psygnal
    - numpy
    - qtpy
    - tifffile

test:
  imports:
    - vollseg_napari
    - vollseg_napari._dock_widget
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python
  requires:
    - pip

about:
  home: https://github.com/kapoorlab/vollseg-napari
  summary: Irregular cell shape segmentation using VollSeg
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kapoorlab
